### PR TITLE
Added info to index.html

### PR DESCRIPTION
**Pull request by FloppaG**

### CODE REVIEW

**Comment by FloppaG** [comment]
I took way too long to do this

**Comment by JunePrimavera** [comment]
https://github.com/TeamPropulsive/TeamPropulsive.github.io/pull/2/commits/0ce67290fb927cd5d3c3a07e393f810189f32953

I dont think we can accept a pr with modified code from another project

**Comment by arthomnix** [comment]
as long as the other project is under a compatible license (which i think it is) i don't see the problem

**Comment by FloppaG** [comment]
> @JunePrimavera [0ce6729](https://github.com/TeamPropulsive/TeamPropulsive.github.io/commit/0ce67290fb927cd5d3c3a07e393f810189f32953)
> 
> I dont think we can accept a pr with modified code from another project

I opened the wrong project then i fixed it

**Pull request merged**
